# Exploring EBay Car Sales Data

## Phase 1: Business Understanding
_This study will analyze car listings scraped from a section of the German EBay website. We will answer the following questions:_

---

## Phase 2: Data Mining
_Finding necessary data to fit the purpose of analysis_

### Data sets
Further information/documentation are available in the source links.
* [Original Dataset on Kaggle](https://www.kaggle.com/orgesleka/used-cars-database/data) contains x0,000 data points
* [`autos.csv`](https://www.kaggle.com/ramamet4/app-store-apple-data-set-10k-apps/home) contains 50,000 data points as sampled by Dataquest.io. This dataset contains the following columns:

| Index | Column name | Definition |
| --- | --- | --- |
| 0 | dateCrawled | when the listing was crawled | 
| 1 | name | name of unit |
| 2 | seller | whether the seller is private or a dealer |
| 3 | offerType | type of listing |
| 4 | price | the price on listing |
| 5 | abtest | whether listing was part of control or test group |
| 6 | vehicleType | type of vehicle |
| 7 | yearOfRegistration | year car was registered |
| 8 | gearbox | the transmission type |
| 9 | powerPS | power of unit in PS |
| 10 | model | the unit's model name |
| 11 | kilometer | how many kms the car has driven |
| 12 | monthOfRegistration | month car was registered |
| 13 | fuelType | the type of fuel used by the unit |
| 14 | brand | brand of unit |
| 15 | notRepairedDamage | whether there is pending repair on the unit |
| 16 | dateCreated | date the listing was created |
| 17 | nrOfPictures | number of pictures in the add |
| 18 | postalCode | the postal code of the vehicle's location |
| 19 | lastSeenOnline | when the crawler saw this ad last |

In [1]:
# Setting up the workspace

import numpy as np
import pandas as pd

autos = pd.read_csv("autos.csv")

In [2]:
# Preliminary review of dataset

autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_T�V_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [3]:
autos.shape

(50000, 20)

In [4]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

In [5]:
autos.describe()

,yearOfRegistration,powerPS,monthOfRegistration,nrOfPictures,postalCode
count,50000.000000,50000.000000,50000.000000,50000.0,50000.000000
mean,2005.073280,116.355920,5.723360,0.0,50813.627300
std,105.712813,209.216627,3.711984,0.0,25779.747957
min,1000.000000,0.000000,0.000000,0.0,1067.000000
25%,1999.000000,70.000000,3.000000,0.0,30451.000000
50%,2003.000000,105.000000,6.000000,0.0,49577.000000
75%,2008.000000,150.000000,9.000000,0.0,71540.000000
max,9999.000000,17700.000000,12.000000,0.0,99998.000000

In [6]:
autos.nunique()

dateCrawled            48213
name                   38754
seller                     2
offerType                  2
price                   2357
abtest                     2
vehicleType                8
yearOfRegistration        97
gearbox                    2
powerPS                  448
model                    245
odometer                  13
monthOfRegistration       13
fuelType                   7
brand                     40
notRepairedDamage          2
dateCreated               76
nrOfPictures               1
postalCode              7014
lastSeen               39481
dtype: int64

In [7]:
autos[autos.duplicated(subset=['name', 'seller', 'offerType', 
                               'price', 'yearOfRegistration', 
                               'monthOfRegistration'], keep='first')]

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
1329,2016-03-13 18:22:16,Opel_Astra_1.6_Caravan_Edition_100_Classic,privat,Angebot,"$1,399",test,kombi,1999,manuell,75,astra,"150,000km",2,benzin,opel,nein,2016-03-13 00:00:00,0,65428,2016-03-17 13:17:14
3978,2016-03-29 15:53:08,320D__177_PS_LIFT_NAVI_KLIMA,privat,Angebot,"$6,000",control,limousine,2009,automatik,177,3er,"125,000km",8,diesel,bmw,nein,2016-03-29 00:00:00,0,21073,2016-03-29 15:53:08
6745,2016-03-19 14:43:13,Touran_1_9TDI_FULL_Leder_Beige_Panorama_Navi,privat,Angebot,"$2,600",test,limousine,2004,manuell,0,touran,"150,000km",9,diesel,volkswagen,NaN,2016-03-19 00:00:00,0,1067,2016-03-19 14:43:13
8063,2016-03-22 17:46:45,XC_90_D5_SPORT_DYNAUDIO_7_SITZE_1.HAND_S_HEFT,privat,Angebot,"$10,000",control,suv,2008,automatik,185,xc_reihe,"90,000km",1,diesel,volvo,nein,2016-03-22 00:00:00,0,10115,2016-03-22 17:46:45
8226,2016-03-24 10:25:22,SHARAN_1.9_LEDER_TOP_/7_SITZE,privat,Angebot,"$2,700",test,kombi,2004,NaN,0,sharan,"150,000km",0,diesel,volkswagen,NaN,2016-03-24 00:00:00,0,55118,2016-03-24 12:07:13
8244,2016-04-04 23:52:38,Mercedes_Benz_SL_380,privat,Angebot,"$6,500",control,cabrio,1985,automatik,204,sl,"150,000km",3,benzin,mercedes_benz,nein,2016-04-04 00:00:00,0,23866,2016-04-07 09:15:18
8432,2016-03-16 11:55:12,Dacia_Logan_MCV_1.5_dCi_Laureate_1._Hand,privat,Angebot,"$2,250",test,kombi,2008,manuell,86,logan,"150,000km",9,diesel,dacia,nein,2016-03-16 00:00:00,0,71636,2016-03-16 11:55:12
8662,2016-03-19 08:36:57,Opel_Corsa_B_1.0,privat,Angebot,$0,test,NaN,2000,NaN,0,corsa,"125,000km",0,NaN,opel,NaN,2016-03-19 00:00:00,0,84066,2016-03-26 16:47:36
8897,2016-03-16 21:57:18,Toyota_Starlet_1.3__75_Ps__T�V_bis_11/2016,privat,Angebot,"$1,150",control,kleinwagen,1995,manuell,75,andere,"150,000km",10,benzin,toyota,NaN,2016-03-16 00:00:00,0,32689,2016-03-23 12:47:32
9036,2016-03-12 15:51:59,Golf_Highline_Diesel_PD_4motion,privat,Angebot,"$1,900",control,limousine,2003,manuell,0,a3,"150,000km",8,diesel,audi,NaN,2016-03-12 00:00:00,0,51065,2016-03-12 15:51:59
9540,2016-03-11 21:50:31,Touareg_3.0_V6_TDI_DPF_Aut._Bi_Xen_1_Hand_Kamera,privat,Angebot,"$10,100",test,suv,2008,automatik,239,touareg,"100,000km",12,diesel,volkswagen,nein,2016-03-11 00:00:00,0,10115,2016-03-11 21:50:31
9618,2016-03-28 18:47:37,Insignia_2.0_DIESEL_FULL_OPTION,privat,Angebot,"$6,000",control,limousine,2010,automatik,160,insignia,"100,000km",9,diesel,opel,nein,2016-03-28 00:00:00,0,13086,2016-03-30 10:18:16
9874,2016-03-06 13:45:50,A6_2.0_TDI_DPF_Garantie_Start_Stop_Navi,privat,Angebot,"$13,000",test,limousine,2011,manuell,177,a6,"80,000km",9,diesel,audi,nein,2016-03-06 00:00:00,0,10115,2016-03-06 13:45:50
10144,2016-04-02 12:51:20,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-04-02 00:00:00,0,81737,2016-04-06 10:46:59
10410,2016-03-12 14:42:28,520_d_Aut._Navi_Prof._Schiebedach__HUD_1_Hand,privat,Angebot,"$12,800",test,limousine,2011,automatik,184,5er,"125,000km",1,diesel,bmw,nein,2016-03-12 00:00:00,0,10115,2016-03-12 14:42:28
10591,2016-03-22 17:48:25,A6_2.0_TDI_DPF_Garantie_Start_Stop_Navi,privat,Angebot,"$13,000",control,limousine,2011,manuell,177,a6,"80,000km",9,diesel,audi,nein,2016-03-22 00:00:00,0,10115,2016-03-22 17:48:25
10705,2016-03-10 13:57:34,A3_2.0_TDI_S_line_Sportpaket_Panorama_Navi,privat,Angebot,"$16,000",test,limousine,2014,automatik,150,a3,"20,000km",3,diesel,audi,nein,2016-03-10 00:00:00,0,10115,2016-03-10 13:57:34
10889,2016-03-10 20:40:47,520_d_Aut._Navi_Prof._Schiebedach__HUD_1_Hand,privat,Angebot,"$12,800",test,limousine,2011,automatik,184,5er,"125,000km",1,diesel,bmw,nein,2016-03-10 00:00:00,0,10115,2016-03-10 20:40:47
10948,2016-03-14 13:54:02,Mini_1.6i_VOLL_LEDER_NAVI_PANORAMA,privat,Angebot,"$4,200",test,andere,2009,automatik,128,cooper,"50,000km",5,benzin,mini,nein,2016-03-14 00:00:00,0,47551,2016-03-14 13:54:02
11028,2016-03-08 17:54:51,520D_Scwartz_TOP_ZUSTAND_!,privat,Angebot,"$3,200",control,limousine,2004,manuell,136,5er,"150,000km",9,diesel,bmw,nein,2016-03-08 00:00:00,0,24568,2016-03-08 17:54:51
11885,2016-03-26 16:50:00,Peugeot_308_SW_Urban_Move,privat,Angebot,"$8,500",control,kombi,2011,manuell,111,3_reihe,"70,000km",3,diesel,peugeot,NaN,2016-03-26 00:00:00,0,86405,2016-04-06 05:17:10
12067,2016-03-09 15:55:30,TOURAN_1.9TDI,privat,Angebot,"$2,900",control,bus,2004,NaN,0,touran,"150,000km",9,diesel,volkswagen,NaN,2016-03-09 00:00:00,0,51065,2016-03-09 16:40:21
12253,2016-03-09 19:45:44,Subaru_Legacy_Kombi__150_PS_Diesel__evtl._mit_...,privat,Angebot,"$3,250",test,kombi,2008,manuell,150,legacy,"150,000km",2,diesel,subaru,ja,2016-03-09 00:00:00,0,84367,2016-03-18 00:15:53
12893,2016-03-10 13:56:39,Touareg_3.0_V6_TDI_DPF_Aut._Bi_Xen_1_Hand_Kamera,privat,Angebot,"$10,100",test,suv,2008,automatik,239,touareg,"100,000km",12,diesel,volkswagen,nein,2016-03-10 00:00:00,0,10115,2016-03-10 14:44:07
13333,2016-03-11 12:47:13,Mercedes_Benz_Mercedes__W201_Oldtimer__Wertgut...,privat,Angebot,"$5,500",test,limousine,1983,automatik,122,andere,"150,000km",9,benzin,mercedes_benz,nein,2016-03-11 00:00:00,0,16766,2016-03-12 16:45:25
13475,2016-03-16 20:57:08,730_d_M_SPORTPAKET_Navi_Prof_1_Hand,privat,Angebot,"$18,000",control,limousine,2010,automatik,245,7er,"60,000km",11,diesel,bmw,nein,2016-03-16 00:00:00,0,10115,2016-03-16 20:57:08
14141,2016-04-04 22:48:10,Audi_A4_Cabriolet_2.4,privat,Angebot,"$6,450",test,cabrio,2002,manuell,170,andere,"150,000km",6,benzin,audi,nein,2016-04-04 00:00:00,0,44147,2016-04-07 01:45:55
14148,2016-04-04 14:59:08,BMW_520d_Aut.,privat,Angebot,"$13,000",test,limousine,2008,automatik,177,5er,"125,000km",10,diesel,bmw,nein,2016-04-04 00:00:00,0,12679,2016-04-06 16:17:53
14282,2016-03-20 15:38:51,530_d_Individual_E39_Zimt_M_Paket,privat,Angebot,"$3,300",control,limousine,2003,manuell,0,5er,"150,000km",9,diesel,bmw,NaN,2016-03-20 00:00:00,0,44267,2016-03-20 15:38:51
14497,2016-03-13 11:06:23,Ford_Fiesta,privat,Angebot,$600,test,kleinwagen,2001,manuell,54,fiesta,"150,000km",3,benzin,ford,NaN,2016-03-13 00:00:00,0,35576,2016-04-01 22:45:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47936,2016-03-24 17:36:44,Golf_GTD_DSG_DCC_Pano_Navi_Sound_Sthzg,privat,Angebot,"$11,000",control,limousine,2014,automatik,185,golf,"20,000km",10,diesel,volkswagen,nein,2016-03-24 00:00:00,0,10115,2016-03-24 17:36:44
47938,2016-03-16 21:45:22,Touran_2.0_TDI_Comfortline_BMT_Aut.Navi_Xenon,privat,Angebot,"$10,500",control,bus,2013,automatik,140,touran,"40,000km",5,diesel,volkswagen,nein,2016-03-16 00:00:00,0,10115,2016-03-16 21:45:22
48034,2016-03-11 19:51:35,PASSAT_1.9TDI_131_PS_HIGHLINE_CHROM_PAKIET,privat,Angebot,"$2,500",test,limousine,2004,manuell,131,passat,"150,000km",9,diesel,volkswagen,nein,2016-03-11 00:00:00,0,48153,2016-03-11 19:51:35
48036,2016-03-15 16:57:34,Insignia_2.0_CDTI_4x4_OPC_Line_Start_Stop_Navi...,privat,Angebot,"$7,500",control,limousine,2011,automatik,160,insignia,"40,000km",10,diesel,opel,nein,2016-03-15 00:00:00,0,10115,2016-03-15 17:40:13
48086,2016-03-19 09:06:35,Zu_verkaufen,privat,Angebot,"$1,400",test,kleinwagen,2003,manuell,80,micra,"125,000km",0,NaN,nissan,NaN,2016-03-19 00:00:00,0,60386,2016-03-23 01:46:52
48126,2016-03-22 17:48:55,A3_2005._1.9_TDi__KLIMA___BNiXENON,privat,Angebot,"$2,800",control,limousine,2005,automatik,105,a3,"150,000km",5,diesel,audi,nein,2016-03-22 00:00:00,0,63128,2016-03-22 17:48:55
48220,2016-03-17 16:55:41,Golf_2_0_Diesel_Individual_NAVI,privat,Angebot,"$2,900",test,limousine,2005,manuell,0,golf,"150,000km",8,diesel,volkswagen,NaN,2016-03-17 00:00:00,0,55118,2016-03-17 16:55:41
48269,2016-03-20 16:37:23,Insignia_2.0_DIESEL_FULL_OPTION,privat,Angebot,"$6,000",test,limousine,2010,automatik,160,insignia,"100,000km",9,diesel,opel,nein,2016-03-20 00:00:00,0,90411,2016-03-20 16:37:23
48411,2016-03-12 13:27:05,Verkaufe_Bmw_5_30d_Navi_Automatik,privat,Angebot,"$6,750",test,limousine,2005,automatik,218,5er,"150,000km",2,diesel,bmw,nein,2016-03-12 00:00:00,0,35435,2016-03-12 14:49:49
48602,2016-03-09 15:56:48,Tiguan_2.0_TDI_4Motion_DSG_Sport&Style,privat,Angebot,"$10,000",control,suv,2011,automatik,140,tiguan,"100,000km",8,diesel,volkswagen,nein,2016-03-09 00:00:00,0,10115,2016-03-09 15:56:48
48632,2016-03-16 00:37:00,Renault_Clio_1.2_16v,privat,Angebot,"$1,100",test,kleinwagen,2002,manuell,75,clio,"150,000km",9,benzin,renault,nein,2016-03-16 00:00:00,0,51145,2016-03-17 06:45:30
48673,2016-03-20 18:58:58,VW_Golf_3_mit_vielen_Umbauten_und_neuem_Tuev,privat,Angebot,$0,test,limousine,1997,manuell,75,golf,"150,000km",0,benzin,volkswagen,nein,2016-03-20 00:00:00,0,15344,2016-03-20 19:41:57
48759,2016-03-28 19:48:44,A3_2.0_TDI_Ambition_1Hand_Top,privat,Angebot,"$2,700",control,limousine,2003,manuell,140,a3,"150,000km",10,diesel,audi,NaN,2016-03-28 00:00:00,0,50129,2016-03-28 19:48:44
48816,2016-03-29 14:37:33,Opel_Astra_Cabrio_1.6i_Bertone_Edition,privat,Angebot,"$2,400",test,cabrio,1999,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-29 00:00:00,0,93152,2016-04-02 01:45:21
49023,2016-03-23 00:49:23,Auto_Audi_A3,privat,Angebot,"$1,900",test,NaN,2017,automatik,125,a3,"150,000km",6,benzin,audi,NaN,2016-03-22 00:00:00,0,40227,2016-04-03 03:16:22
49056,2016-03-10 15:52:24,Mercedes_Benz_Mercedes__W201_Oldtimer__Wertgut...,privat,Angebot,"$5,500",test,limousine,1983,automatik,122,andere,"150,000km",9,benzin,mercedes_benz,nein,2016-03-10 00:00:00,0,16766,2016-03-11 03:45:00
49090,2016-03-10 11:50:11,Honda_Civic_1.8i_VTEC,privat,Angebot,"$7,600",test,limousine,2008,manuell,140,civic,"90,000km",7,benzin,honda,nein,2016-03-10 00:00:00,0,95615,2016-03-10 11:50:11
49262,2016-03-26 18:31:21,Opel_vectra,privat,Angebot,"$2,000",test,NaN,2018,NaN,0,NaN,"150,000km",0,NaN,opel,NaN,2016-03-26 00:00:00,0,65549,2016-04-06 18:19:01
49401,2016-03-28 18:47:25,Mercedes_Benz_E_200_T_CGI__Autom__Leder__8_fac...,privat,Angebot,"$21,780",control,kombi,2010,automatik,184,e_klasse,"80,000km",10,benzin,mercedes_benz,nein,2016-03-28 00:00:00,0,81547,2016-04-01 03:46:40
49490,2016-03-09 17:56:39,TOURAN_1.9TDI,privat,Angebot,"$2,900",test,bus,2004,NaN,0,touran,"150,000km",9,diesel,volkswagen,NaN,2016-03-09 00:00:00,0,51065,2016-03-09 17:56:39
49493,2016-03-28 08:58:34,Mercedes_Benz_Vaneo_1_9_Kombi_/_Van_/_Hochdach,privat,Angebot,"$2,300",test,bus,2002,manuell,125,v_klasse,"150,000km",12,benzin,mercedes_benz,NaN,2016-03-28 00:00:00,0,76185,2016-03-28 10:40:19
49573,2016-03-23 19:53:59,A4_Diesel_Leder_Top___NAVI,privat,Angebot,"$2,400",control,limousine,2004,NaN,0,a4,"150,000km",9,diesel,audi,NaN,2016-03-23 00:00:00,0,40210,2016-03-23 19:53:59
49672,2016-03-19 18:53:13,Opel_Agila_1.0_12_V,privat,Angebot,$899,test,kleinwagen,2001,manuell,58,agila,"150,000km",6,benzin,opel,nein,2016-03-19 00:00:00,0,55128,2016-04-04 03:47:18
49774,2016-03-08 14:51:37,320_d_Edition_Sport,privat,Angebot,"$2,200",test,limousine,2003,NaN,0,3er,"150,000km",11,diesel,bmw,nein,2016-03-08 00:00:00,0,34454,2016-03-08 14:51:37
49893,2016-03-15 13:58:31,Mitsubishi_Pajero_3.2_DI_D_Automatik_Instyle,privat,Angebot,"$19,500",control,suv,2007,automatik,170,pajero,"60,000km",6,diesel,mitsubishi,nein,2016-03-15 00:00:00,0,91522,2016-03-22 15:17:52
49945,2016-04-04 12:54:29,omega_2_2_facelift_mit_neuem_tuev,privat,Angebot,"$1,750",control,kombi,1999,manuell,144,omega,"150,000km",12,benzin,opel,nein,2016-04-04 00:00:00,0,12355,2016-04-06 14:45:14
49955,2016-03-30 12:50:18,Golf_1.9_TDI_DPF_4mot_GT_Sport,privat,Angebot,"$3,400",control,limousine,2008,NaN,0,golf,"150,000km",11,diesel,volkswagen,nein,2016-03-30 00:00:00,0,83512,2016-03-30 12:50:18
49960,2016-03-25 22:51:55,Ford_KA_zu_verschenken_***Reserviert***,privat,Angebot,$0,control,kleinwagen,1999,manuell,60,ka,"150,000km",6,benzin,ford,NaN,2016-03-25 00:00:00,0,34355,2016-03-25 22:51:55
49961,2016-03-14 19:06:17,Golf_2.0_TDI_Sportline_Sonderproduktion,privat,Angebot,"$3,200",control,limousine,2007,manuell,140,golf,"150,000km",7,diesel,volkswagen,NaN,2016-03-14 00:00:00,0,65760,2016-03-14 19:06:17
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06

### Observations

1. `autos.csv` has  50,000 rows and 20 columns. Out of the 20 columns: 15 store values as strings and 5 as integers. We will alter these in the next phase.
2. There are null values in 5 columns namely `vehicleType`, `gearbox`, `model`, `fuelType`, and `notRepairedDamage`. The last one has 9,829 null values which is around 19.66% of the whole series.
3. There are 13 unique values in `monthOfRegistration` when it should only be 12 at most.
4. `nrOfPictures` has the same values in the whole column, making it pointless to keep.
5. We want to rearrange the columns to make better sense of information (ie: cluster columns based on whether they describe the unit or the listing).
6. Column names are in camelCase instead of the preferred snake_case.
7. Some names of columns, `odometer` and `powerPS` for example, are not consistent in showing the unit of values in the column.

-----

## Phase 3: Data Cleaning
_Making sure the data set is primed for analysis by doing the following:_

1. Renaming columns
2. Deleting columns
3. Rearranging columns
4. Changing dtypes
5. Removing duplicates
6. Fix `monthOfRegistration` values
7. Reviewing columns where values are almost the same
8. Cleaning numeric columns with unrealistic values

In [8]:
# 1. Renaming columns
autos.rename(columns={'dateCrawled' : 'crawl_date',
                      'offerType' : 'offer_type', 
                      'vehicleType' : 'vehicle_type', 
                      'yearOfRegistration' : 'reg_year', 
                      'powerPS' : 'power_ps', 
                      'odometer' : 'mileage_km', 
                      'monthOfRegistration' : 'reg_month', 
                      'fuelType' : 'fuel_type', 
                      'notRepairedDamage' : 'unrepaired_damage', 
                      'dateCreated' : 'ad_created', 
                      'nrOfPictures' : 'no_pictures', 
                      'postalCode' : 'postal_code',
                      'lastSeen' : 'last_seen'}, inplace=True)

In [9]:
# 2. Deleting columns
autos.drop(columns='no_pictures')

,crawl_date,name,seller,offer_type,price,abtest,vehicle_type,reg_year,gearbox,power_ps,model,mileage_km,reg_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_T�V_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___T�V_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

In [10]:
# 3. Rearranging columns
autos = autos[['crawl_date', 
               'name', 'seller', 'postal_code', 
               'offer_type', 'price', 
               'reg_year', 'reg_month', 
               'vehicle_type', 'brand', 'model',  
               'gearbox', 'fuel_type', 'power_ps', 
               'mileage_km', 'unrepaired_damage', 
               'abtest', 'ad_created', 'last_seen']]

In [11]:
# 4. Changing dtypes
autos['crawl_date'] = pd.to_datetime(autos['crawl_date'], format='%Y-%m-%d %H:%M:%S')

autos['price'] = autos['price'].str.replace('$', '')
autos['price'] = autos['price'].str.replace(',', '')
autos['price'] = autos['price'].astype(int)

autos['reg_year'] = autos['reg_year'].astype(int)

autos['reg_month'] = autos['reg_month'].astype(int)

autos['mileage_km'] = autos['mileage_km'].str.replace('km', '')
autos['mileage_km'] = autos['mileage_km'].str.replace(',', '')
autos['mileage_km'] = autos['mileage_km'].astype(int)

autos['ad_created'] = pd.to_datetime(autos['ad_created'], format='%Y-%m-%d %H:%M:%S')

autos['last_seen'] = pd.to_datetime(autos['last_seen'], format='%Y-%m-%d %H:%M:%S')

In [12]:
autos.info() # new dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
crawl_date           50000 non-null datetime64[ns]
name                 50000 non-null object
seller               50000 non-null object
postal_code          50000 non-null int64
offer_type           50000 non-null object
price                50000 non-null int64
reg_year             50000 non-null int64
reg_month            50000 non-null int64
vehicle_type         44905 non-null object
brand                50000 non-null object
model                47242 non-null object
gearbox              47320 non-null object
fuel_type            45518 non-null object
power_ps             50000 non-null int64
mileage_km           50000 non-null int64
unrepaired_damage    40171 non-null object
abtest               50000 non-null object
ad_created           50000 non-null datetime64[ns]
last_seen            50000 non-null datetime64[ns]
dtypes: datetime64[ns](3), int64(6), object(10)
memory usage: 7.2+ MB

In [13]:
# 5. Removing duplicates based on a subset of columns
autos.drop_duplicates(subset=['name', 'seller', 'offer_type', 
                              'price', 'reg_year', 'reg_month'],
                              keep='last')

,crawl_date,name,seller,postal_code,offer_type,price,reg_year,reg_month,vehicle_type,brand,model,gearbox,fuel_type,power_ps,mileage_km,unrepaired_damage,abtest,ad_created,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,79588,Angebot,5000,2004,3,bus,peugeot,andere,manuell,lpg,158,150000,nein,control,2016-03-26,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,71034,Angebot,8500,1997,6,limousine,bmw,7er,automatik,benzin,286,150000,nein,control,2016-04-04,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,35394,Angebot,8990,2009,7,limousine,volkswagen,golf,manuell,benzin,102,70000,nein,test,2016-03-26,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,33729,Angebot,4350,2007,6,kleinwagen,smart,fortwo,automatik,benzin,71,70000,nein,control,2016-03-12,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_T�V_neu_ist_sehr_gepfleg...,privat,39218,Angebot,1350,2003,7,kombi,ford,focus,manuell,benzin,0,150000,nein,test,2016-04-01,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,22962,Angebot,7900,2006,4,bus,chrysler,voyager,automatik,diesel,150,150000,NaN,test,2016-03-21,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,31535,Angebot,300,1995,8,limousine,volkswagen,golf,manuell,benzin,90,150000,NaN,test,2016-03-20,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,53474,Angebot,1990,1998,12,limousine,volkswagen,golf,manuell,diesel,90,150000,nein,control,2016-03-16,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,7426,Angebot,250,2000,10,NaN,seat,arosa,manuell,NaN,0,150000,nein,test,2016-03-22,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,15749,Angebot,590,1997,7,bus,renault,megane,manuell,benzin,90,150000,nein,control,2016-03-16,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,86157,Angebot,999,2017,4,NaN,volkswagen,NaN,manuell,benzin,90,150000,nein,test,2016-03-14,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,17498,Angebot,350,2000,0,NaN,mercedes_benz,NaN,NaN,benzin,0,150000,NaN,control,2016-03-16,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,34590,Angebot,5299,2010,9,kleinwagen,smart,fortwo,automatik,benzin,71,50000,nein,control,2016-03-31,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,12043,Angebot,1350,1999,11,limousine,audi,a3,manuell,benzin,101,150000,nein,control,2016-03-23,2016-04-01 14:17:13
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,61276,Angebot,18900,1982,6,coupe,sonstige_autos,NaN,automatik,benzin,203,80000,nein,test,2016-04-01,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,57299,Angebot,350,1999,5,kombi,opel,vectra,manuell,benzin,101,150000,nein,test,2016-03-16,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,74821,Angebot,5500,1990,6,coupe,volkswagen,scirocco,manuell,benzin,205,150000,nein,test,2016-03-29,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,54329,Angebot,300,1995,0,bus,bmw,3er,manuell,benzin,150,150000,NaN,control,2016-03-26,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,40878,Angebot,4150,2004,2,suv,mazda,andere,manuell,lpg,124,150000,nein,control,2016-03-17,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,53913,Angebot,3500,2003,5,kombi,audi,a4,manuell,diesel,131,150000,NaN,test,2016-03-05,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,65428,Angebot,41500,2004,4,cabrio,porsche,911,manuell,benzin,320,150000,nein,test,2016-03-06,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,44789,Angebot,25450,2015,1,cabrio,mini,cooper,manuell,benzin,184,10000,nein,control,2016-03-28,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,30900,Angebot,7999,2010,2,bus,peugeot,NaN,manuell,diesel,120,150000,nein,control,2016-03-10,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,22547,Angebot,48500,2014,12,limousine,bmw,5er,automatik,benzin,306,30000,nein,control,2016-04-03,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,27574,Angebot,90,1996,4,kombi,ford,NaN,manuell,benzin,116,150000,ja,control,2016-03-21,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,38110,Angebot,777,1992,2,kleinwagen,volkswagen,polo,manuell,benzin,54,125000,nein,control,2016-04-03,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,66701,Angebot,0,2005,0,NaN,ford,NaN,NaN,NaN,0,150000,NaN,control,2016-03-27,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,15745,Angebot,5250,2007,7,kleinwagen,mini,cooper,manuell,diesel,110,150000,ja,control,2016-03-19,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,47638,Angebot,4999,2004,10,kombi,mercedes_benz,e_klasse,automatik,diesel,204,150000,nein,test,2016-04-02,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,57076,Angebot,80,2002,6,kleinwagen,peugeot,2_reihe,manuell,benzin,60,150000,ja,test,2016-03-14,2016-03-14 11:47:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,14947,Angebot,15800,2010,4,bus,citroen,c4,automatik,diesel,136,60000,nein,control,2016-03-21,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,65197,Angebot,950,2001,4,kleinwagen,volkswagen,lupo,manuell,benzin,50,150000,nein,test,2016-03-29,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,65326,Angebot,3300,2004,10,bus,mercedes_benz,vito,automatik,diesel,150,150000,ja,control,2016-03-26,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,53567,Angebot,6000,2004,11,cabrio,mercedes_benz,slk,manuell,benzin,163,150000,nein,control,2016-03-27,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,8209,Angebot,0,1983,2,cabrio,volkswagen,golf,manuell,benzin,70,150000,nein,control,2016-03-20,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,84385,Angebot,9700,2012,11,kleinwagen,honda,jazz,automatik,hybrid,88,100000,nein,control,2016-03-27,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,36100,Angebot,5900,1992,12,kombi,audi,80,automatik,benzin,150,150000,nein,test,2016-03-19,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,33739,Angebot,5500,2003,2,limousine,mercedes_benz,c_klasse,manuell,diesel,116,150000,nein,control,2016-03-31,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,24405,Angebot,900,1996,9,limousine,mercedes_benz,e_klasse,automatik,benzin,136,150000,ja,control,2016-04-04,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,48455,Angebot,11000,2011,11,kleinwagen,volkswagen,polo,manuell,diesel,90,70000,nein,test,2016-03-20,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,56218,Angebot,400,1995,3,kombi,ford,escort,manuell,benzin,105,125000,NaN,control,2016-03-12,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,86859,Angebot,2000,1998,12,kombi,opel,astra,manuell,benzin,115,150000,nein,control,2016-03-15,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,45884,Angebot,1950,2004,7,kleinwagen,skoda,fabia,manuell,benzin,0,90000,NaN,control,2016-03-29,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,52477,Angebot,600,1999,4,kleinwagen,ford,focus,manuell,benzin,101,150000,NaN,test,2016-03-06,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,12103,Angebot,0,2000,0,NaN,sonstige_autos,NaN,NaN,NaN,0,150000,NaN,test,2016-03-31,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,30900,Angebot,1000,1995,0,NaN,volkswagen,NaN,automatik,benzin,0,150000,NaN,control,2016-04-02,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,73527,Angebot,15900,2010,11,limousine,chrysler,300c,automatik,diesel,218,125000,nein,control,2016-04-04,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,94362,Angebot,21990,2013,11,limousine,audi,a3,manuell,diesel,150,50000,nein,control,2016-03-22,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,83646,Angebot,9550,2001,10,coupe,bmw,3er,manuell,benzin,231,150000,nein,control,2016-03-28,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,21244,Angebot,150,1997,5,kleinwagen,volkswagen,polo,manuell,benzin,0,150000,ja,test,2016-03-11,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,58239,Angebot,17500,2012,12,limousine,mercedes_benz,a_klasse,manuell,benzin,156,30000,nein,test,2016-03-21,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,61350,Angebot,500,2016,0,NaN,renault,twingo,manuell,benzin,0,150000,NaN,control,2016-03-06,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,68642,Angebot,4800,2009,9,kleinwagen,fiat,andere,manuell,lpg,120,125000,nein,control,2016-03-10,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,65203,Angebot,1650,1997,7,kleinwagen,audi,NaN,manuell,benzin,0,150000,NaN,control,2016-03-15,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,46537,Angebot,5000,2001,1,kombi,audi,a6,automatik,benzin,299,150000,nein,control,2016-03-22,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,82131,Angebot,24900,2011,1,limousine,audi,q5,automatik,diesel,239,100000,nein,control,2016-03-27,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___T�V_neu+...,privat,44807,Angebot,1980,1996,5,cabrio,opel,astra,manuell,benzin,75,150000,nein,control,2016-03-28,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,73430,Angebot,13200,2014,11,cabrio,fiat,500,automatik,benzin,69,5000,nein,test,2016-04-02,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,35683,Angebot,22900,2013,11,kombi,audi,a3,manuell,diesel,150,40000,nein,control,2016-03-08,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,45897,Angebot,1250,1996,1,limousine,opel,vectra,manuell,benzin,101,150000,nein,control,2016-03-13,2016-04-06 21:18:48

In [14]:
# 6. Fixing reg_year and reg_month values
autos['reg_year'].value_counts().sort_index().head(10)

1000    1
1001    1
1111    1
1500    1
1800    2
1910    9
1927    1
1929    1
1931    1
1934    2
Name: reg_year, dtype: int64

In [15]:
autos['reg_year'].value_counts().sort_index().tail(10)

4100    1
4500    1
4800    1
5000    4
5911    1
6200    1
8888    1
9000    2
9996    1
9999    4
Name: reg_year, dtype: int64

The first model of the modern automobile was built by Karl Benz in 1886. Based on the dataset [documentation](https://www.kaggle.com/orgesleka/used-cars-database/metadata), it was uploaded in November 20, 2016. All entries that don't fall within 1886 and 2016 will be dropped. <br/>
Reference: [1](https://www.livescience.com/37538-who-invented-the-car.html)

In [16]:
filtered = autos[(autos['reg_year'] < 1886) | (autos['reg_year'] > 2016)].index
autos.drop(filtered , inplace=True)

In [17]:
autos['reg_month'].value_counts().sort_index()

0     4587
1     3164
2     2916
3     4899
4     3954
5     3949
6     4211
7     3812
8     3085
9     3301
10    3554
11    3271
12    3325
Name: reg_month, dtype: int64

Because 10% of the remaining `reg_month` value are `0`, dropping based on this condition might significantly alter the results of the study. It has been decided to not include this column in the analysis instead.

In [18]:
autos.drop(columns='reg_month')

,crawl_date,name,seller,postal_code,offer_type,price,reg_year,vehicle_type,brand,model,gearbox,fuel_type,power_ps,mileage_km,unrepaired_damage,abtest,ad_created,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,79588,Angebot,5000,2004,bus,peugeot,andere,manuell,lpg,158,150000,nein,control,2016-03-26,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,71034,Angebot,8500,1997,limousine,bmw,7er,automatik,benzin,286,150000,nein,control,2016-04-04,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,35394,Angebot,8990,2009,limousine,volkswagen,golf,manuell,benzin,102,70000,nein,test,2016-03-26,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,33729,Angebot,4350,2007,kleinwagen,smart,fortwo,automatik,benzin,71,70000,nein,control,2016-03-12,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_T�V_neu_ist_sehr_gepfleg...,privat,39218,Angebot,1350,2003,kombi,ford,focus,manuell,benzin,0,150000,nein,test,2016-04-01,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,22962,Angebot,7900,2006,bus,chrysler,voyager,automatik,diesel,150,150000,NaN,test,2016-03-21,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,31535,Angebot,300,1995,limousine,volkswagen,golf,manuell,benzin,90,150000,NaN,test,2016-03-20,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,53474,Angebot,1990,1998,limousine,volkswagen,golf,manuell,diesel,90,150000,nein,control,2016-03-16,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,7426,Angebot,250,2000,NaN,seat,arosa,manuell,NaN,0,150000,nein,test,2016-03-22,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,15749,Angebot,590,1997,bus,renault,megane,manuell,benzin,90,150000,nein,control,2016-03-16,2016-04-06 10:46:35
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,17498,Angebot,350,2000,NaN,mercedes_benz,NaN,NaN,benzin,0,150000,NaN,control,2016-03-16,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,34590,Angebot,5299,2010,kleinwagen,smart,fortwo,automatik,benzin,71,50000,nein,control,2016-03-31,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,12043,Angebot,1350,1999,limousine,audi,a3,manuell,benzin,101,150000,nein,control,2016-03-23,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,81737,Angebot,3999,2007,kleinwagen,renault,clio,manuell,benzin,75,150000,NaN,test,2016-03-23,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,61276,Angebot,18900,1982,coupe,sonstige_autos,NaN,automatik,benzin,203,80000,nein,test,2016-04-01,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,57299,Angebot,350,1999,kombi,opel,vectra,manuell,benzin,101,150000,nein,test,2016-03-16,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,74821,Angebot,5500,1990,coupe,volkswagen,scirocco,manuell,benzin,205,150000,nein,test,2016-03-29,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,54329,Angebot,300,1995,bus,bmw,3er,manuell,benzin,150,150000,NaN,control,2016-03-26,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,40878,Angebot,4150,2004,suv,mazda,andere,manuell,lpg,124,150000,nein,control,2016-03-17,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,53913,Angebot,3500,2003,kombi,audi,a4,manuell,diesel,131,150000,NaN,test,2016-03-05,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,65428,Angebot,41500,2004,cabrio,porsche,911,manuell,benzin,320,150000,nein,test,2016-03-06,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,44789,Angebot,25450,2015,cabrio,mini,cooper,manuell,benzin,184,10000,nein,control,2016-03-28,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,30900,Angebot,7999,2010,bus,peugeot,NaN,manuell,diesel,120,150000,nein,control,2016-03-10,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,22547,Angebot,48500,2014,limousine,bmw,5er,automatik,benzin,306,30000,nein,control,2016-04-03,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,27574,Angebot,90,1996,kombi,ford,NaN,manuell,benzin,116,150000,ja,control,2016-03-21,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,38110,Angebot,777,1992,kleinwagen,volkswagen,polo,manuell,benzin,54,125000,nein,control,2016-04-03,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,66701,Angebot,0,2005,NaN,ford,NaN,NaN,NaN,0,150000,NaN,control,2016-03-27,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,15745,Angebot,5250,2007,kleinwagen,mini,cooper,manuell,diesel,110,150000,ja,control,2016-03-19,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,47638,Angebot,4999,2004,kombi,mercedes_benz,e_klasse,automatik,diesel,204,150000,nein,test,2016-04-02,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,57076,Angebot,80,2002,kleinwagen,peugeot,2_reihe,manuell,benzin,60,150000,ja,test,2016-03-14,2016-03-14 11:47:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,14947,Angebot,15800,2010,bus,citroen,c4,automatik,diesel,136,60000,nein,control,2016-03-21,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,65197,Angebot,950,2001,kleinwagen,volkswagen,lupo,manuell,benzin,50,150000,nein,test,2016-03-29,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,65326,Angebot,3300,2004,bus,mercedes_benz,vito,automatik,diesel,150,150000,ja,control,2016-03-26,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,53567,Angebot,6000,2004,cabrio,mercedes_benz,slk,manuell,benzin,163,150000,nein,control,2016-03-27,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,8209,Angebot,0,1983,cabrio,volkswagen,golf,manuell,benzin,70,150000,nein,control,2016-03-20,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,84385,Angebot,9700,2012,kleinwagen,honda,jazz,automatik,hybrid,88,100000,nein,control,2016-03-27,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,36100,Angebot,5900,1992,kombi,audi,80,automatik,benzin,150,150000,nein,test,2016-03-19,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,33739,Angebot,5500,2003,limousine,mercedes_benz,c_klasse,manuell,diesel,116,150000,nein,control,2016-03-31,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,24405,Angebot,900,1996,limousine,mercedes_benz,e_klasse,automatik,benzin,136,150000,ja,control,2016-04-04,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,48455,Angebot,11000,2011,kleinwagen,volkswagen,polo,manuell,diesel,90,70000,nein,test,2016-03-20,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,56218,Angebot,400,1995,kombi,ford,escort,manuell,benzin,105,125000,NaN,control,2016-03-12,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,86859,Angebot,2000,1998,kombi,opel,astra,manuell,benzin,115,150000,nein,control,2016-03-15,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,45884,Angebot,1950,2004,kleinwagen,skoda,fabia,manuell,benzin,0,90000,NaN,control,2016-03-29,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,52477,Angebot,600,1999,kleinwagen,ford,focus,manuell,benzin,101,150000,NaN,test,2016-03-06,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,12103,Angebot,0,2000,NaN,sonstige_autos,NaN,NaN,NaN,0,150000,NaN,test,2016-03-31,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,30900,Angebot,1000,1995,NaN,volkswagen,NaN,automatik,benzin,0,150000,NaN,control,2016-04-02,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,73527,Angebot,15900,2010,limousine,chrysler,300c,automatik,diesel,218,125000,nein,control,2016-04-04,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,94362,Angebot,21990,2013,limousine,audi,a3,manuell,diesel,150,50000,nein,control,2016-03-22,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,83646,Angebot,9550,2001,coupe,bmw,3er,manuell,benzin,231,150000,nein,control,2016-03-28,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,21244,Angebot,150,1997,kleinwagen,volkswagen,polo,manuell,benzin,0,150000,ja,test,2016-03-11,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,58239,Angebot,17500,2012,limousine,mercedes_benz,a_klasse,manuell,benzin,156,30000,nein,test,2016-03-21,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,61350,Angebot,500,2016,NaN,renault,twingo,manuell,benzin,0,150000,NaN,control,2016-03-06,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,68642,Angebot,4800,2009,kleinwagen,fiat,andere,manuell,lpg,120,125000,nein,control,2016-03-10,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,65203,Angebot,1650,1997,kleinwagen,audi,NaN,manuell,benzin,0,150000,NaN,control,2016-03-15,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,46537,Angebot,5000,2001,kombi,audi,a6,automatik,benzin,299,150000,nein,control,2016-03-22,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,82131,Angebot,24900,2011,limousine,audi,q5,automatik,diesel,239,100000,nein,control,2016-03-27,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___T�V_neu+...,privat,44807,Angebot,1980,1996,cabrio,opel,astra,manuell,benzin,75,150000,nein,control,2016-03-28,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,73430,Angebot,13200,2014,cabrio,fiat,500,automatik,benzin,69,5000,nein,test,2016-04-02,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,35683,Angebot,22900,2013,kombi,audi,a3,manuell,diesel,150,40000,nein,control,2016-03-08,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,45897,Angebot,1250,1996,limousine,opel,vectra,manuell,benzin,101,150000,nein,control,2016-03-13,2016-04-06 21:18:48

In [19]:
# 7. Reviewing columns where values are almost the same
# Referred to autos.nunique()

autos['seller'].value_counts()

privat        48027
gewerblich        1
Name: seller, dtype: int64

In [20]:
autos.loc[autos['seller'] == 'gewerblich']

,crawl_date,name,seller,postal_code,offer_type,price,reg_year,reg_month,vehicle_type,brand,model,gearbox,fuel_type,power_ps,mileage_km,unrepaired_damage,abtest,ad_created,last_seen
7738,2016-03-15 18:06:22,Verkaufe_mehrere_Fahrzeuge_zum_Verschrotten,gewerblich,65232,Angebot,100,2000,8,kombi,renault,megane,manuell,benzin,0,150000,NaN,control,2016-03-15,2016-04-06 17:15:37

In [21]:
autos = autos.drop(7738, axis=0)

In [22]:
autos['offer_type'].value_counts()

Angebot    48026
Gesuch         1
Name: offer_type, dtype: int64

In [23]:
autos.loc[autos['offer_type'] == 'Gesuch']

,crawl_date,name,seller,postal_code,offer_type,price,reg_year,reg_month,vehicle_type,brand,model,gearbox,fuel_type,power_ps,mileage_km,unrepaired_damage,abtest,ad_created,last_seen
17541,2016-04-03 15:48:33,Suche_VW_T5_Multivan,privat,29690,Gesuch,0,2005,0,bus,volkswagen,transporter,NaN,NaN,0,150000,NaN,test,2016-04-03,2016-04-05 15:16:06

In [24]:
autos = autos.drop(17541, axis=0)

In [25]:
autos['gearbox'].value_counts()

manuell      35559
automatik    10044
Name: gearbox, dtype: int64

In [26]:
autos['unrepaired_damage'].value_counts()

nein    34255
ja       4785
Name: unrepaired_damage, dtype: int64

In [27]:
autos['abtest'].value_counts()

test       24755
control    23271
Name: abtest, dtype: int64

In [28]:
autos.shape

(48026, 19)

In [29]:
# 8. Cleaning numeric columns with unrealistic values

autos.describe()

,postal_code,price,reg_year,reg_month,power_ps,mileage_km
count,48026.000000,4.802600e+04,48026.000000,48026.000000,48026.000000,48026.000000
mean,50936.012035,9.585649e+03,2002.803523,5.767834,117.075293,125543.143297
std,25792.352174,4.843918e+05,7.310985,3.696771,195.153879,40107.276010
min,1067.000000,0.000000e+00,1910.000000,0.000000,0.000000,5000.000000
25%,30459.000000,1.150000e+03,1999.000000,3.000000,71.000000,100000.000000
50%,49696.000000,2.990000e+03,2003.000000,6.000000,107.000000,150000.000000
75%,71665.000000,7.400000e+03,2008.000000,9.000000,150.000000,150000.000000
max,99998.000000,1.000000e+08,2016.000000,12.000000,17700.000000,150000.000000

Some values in `price` and `power_ps` appear to be beyond the normal range.

In [30]:
autos['price'].value_counts().sort_index().head(15)

0     1334
1      150
2        2
3        1
5        2
8        1
9        1
10       6
11       2
12       3
13       2
14       1
15       2
17       3
18       1
Name: price, dtype: int64

In [31]:
autos['price'].value_counts().sort_index().tail(15)

265000      1
295000      1
299000      1
345000      1
350000      1
999990      1
999999      2
1234566     1
1300000     1
3890000     1
10000000    1
11111111    2
12345678    1
27322222    1
99999999    1
Name: price, dtype: int64

After inspecting the value_counts for `price` and looking into the price of current most expensive car. We decide to remove rows whose `price` fall outside 100 and 13,000,000.

In [32]:
filtered = autos[(autos['price'] < 100) | (autos['price'] > 13000000)].index
autos.drop(filtered , inplace=True)

In [33]:
autos.shape

(46361, 19)

In [34]:
autos['power_ps'].value_counts().sort_index().head(15)

0     4339
1        4
2        2
3        2
4        4
5       12
6        3
8        2
9        1
10       2
11       4
14       1
15       5
16       1
18       6
Name: power_ps, dtype: int64

In [35]:
autos['power_ps'].value_counts().sort_index().tail(15)

1998     1
2729     1
3500     1
3750     1
4400     1
5867     1
6045     1
6226     1
6512     1
7511     1
8404     1
14009    1
15001    1
16312    1
17700    1
Name: power_ps, dtype: int64

Based on research, the minimum power required for an average car is 20 HP (around 20.27 PS). The most powerful car for 2018 is Rimac C_Two at 1,887 BHP (around 1913.17 PS). In the next cell, we are dropping rows that don't fall in this range.

References: [1](https://hypertextbook.com/facts/2001/JaeheeJoh.shtml), [2](https://www.topgear.com/car-news/best-2018/15-fastest-and-most-powerful-cars-2018)

In [36]:
filtered = autos[(autos['power_ps'] < 20.27) | (autos['power_ps'] > 1913.17)].index
autos.drop(filtered , inplace=True)

In [37]:
autos.shape

(41951, 19)

### Preview of clean data

In [38]:
autos.head()

,crawl_date,name,seller,postal_code,offer_type,price,reg_year,reg_month,vehicle_type,brand,model,gearbox,fuel_type,power_ps,mileage_km,unrepaired_damage,abtest,ad_created,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,79588,Angebot,5000,2004,3,bus,peugeot,andere,manuell,lpg,158,150000,nein,control,2016-03-26,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,71034,Angebot,8500,1997,6,limousine,bmw,7er,automatik,benzin,286,150000,nein,control,2016-04-04,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,35394,Angebot,8990,2009,7,limousine,volkswagen,golf,manuell,benzin,102,70000,nein,test,2016-03-26,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,33729,Angebot,4350,2007,6,kleinwagen,smart,fortwo,automatik,benzin,71,70000,nein,control,2016-03-12,2016-03-15 03:16:28
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,22962,Angebot,7900,2006,4,bus,chrysler,voyager,automatik,diesel,150,150000,NaN,test,2016-03-21,2016-04-06 09:45:21

In [39]:
autos.shape

(41951, 19)

In [40]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41951 entries, 0 to 49999
Data columns (total 19 columns):
crawl_date           41951 non-null datetime64[ns]
name                 41951 non-null object
seller               41951 non-null object
postal_code          41951 non-null int64
offer_type           41951 non-null object
price                41951 non-null int64
reg_year             41951 non-null int64
reg_month            41951 non-null int64
vehicle_type         40497 non-null object
brand                41951 non-null object
model                40371 non-null object
gearbox              41248 non-null object
fuel_type            39826 non-null object
power_ps             41951 non-null int64
mileage_km           41951 non-null int64
unrepaired_damage    36042 non-null object
abtest               41951 non-null object
ad_created           41951 non-null datetime64[ns]
last_seen            41951 non-null datetime64[ns]
dtypes: datetime64[ns](3), int64(6), object(10)
memory usage: 6.4+ MB

In [41]:
autos.describe()

,postal_code,price,reg_year,reg_month,power_ps,mileage_km
count,41951.000000,4.195100e+04,41951.000000,41951.000000,41951.000000,41951.000000
mean,51604.317108,7.314194e+03,2003.184644,5.995471,127.925008,125441.824986
std,25731.782610,9.747684e+04,6.805473,3.574866,71.830966,39366.886424
min,1067.000000,1.000000e+02,1927.000000,0.000000,21.000000,5000.000000
25%,31191.000000,1.400000e+03,1999.000000,3.000000,80.000000,100000.000000
50%,50765.000000,3.500000e+03,2003.000000,6.000000,116.000000,150000.000000
75%,72461.000000,7.999000e+03,2008.000000,9.000000,150.000000,150000.000000
max,99998.000000,1.234568e+07,2016.000000,12.000000,1800.000000,150000.000000

-----

## Phase 4: Data Exploration
_Form hypothesis about the data_

In [42]:
autos['brand'].value_counts(sort=True)

volkswagen        8911
bmw               4787
opel              4428
mercedes_benz     4062
audi              3763
ford              2868
renault           1869
peugeot           1245
fiat              1030
seat               775
skoda              719
mazda              645
nissan             621
smart              585
citroen            579
toyota             544
hyundai            430
mini               395
volvo              393
mitsubishi         343
honda              336
sonstige_autos     317
kia                299
alfa_romeo         284
porsche            264
suzuki             249
chevrolet          232
chrysler           148
dacia              114
jeep                98
daihatsu            95
subaru              91
land_rover          91
saab                72
jaguar              64
daewoo              53
rover               50
lancia              43
trabant             38
lada                21
Name: brand, dtype: int64

### Focus on popular brands

In [43]:
popular_brands = autos['brand'].value_counts(sort=True)[:9].index.tolist()

In [44]:
popular_brands

['volkswagen',
 'bmw',
 'opel',
 'mercedes_benz',
 'audi',
 'ford',
 'renault',
 'peugeot',
 'fiat']

In [45]:
popular_autos = autos[autos['brand'].isin(popular_brands)] # working dataset sliced from autos

In [46]:
popular_autos.shape

(32963, 19)

In [47]:
zeros = [0] * 9 # creates a placeholder list

In [48]:
brand_stats = pd.DataFrame(list(zip(popular_brands, zeros))
                           , columns = ['brand' , 'zeros']) # converts lists to pd dataframe

In [49]:
brand_stats = brand_stats.set_index('brand') # sets brand as index for when we add columns later

In [50]:
brand_stats

               zeros
brand
volkswagen         0
bmw                0
opel               0
mercedes_benz      0
audi               0
ford               0
renault            0
peugeot            0
fiat               0

In [51]:
brand_stats['ave_price'] = popular_autos.groupby('brand')['price'].mean()
brand_stats['ave_mileage_km'] = popular_autos.groupby('brand')['mileage_km'].mean()
brand_stats['ave_power_ps'] = popular_autos.groupby('brand')['power_ps'].mean()
brand_stats.drop(columns='zeros')

                 ave_price  ave_mileage_km  ave_power_ps
brand
volkswagen     5933.477949   128272.360004    107.958029
bmw            8874.688531   132594.526844    174.761228
opel           5959.799006   129101.174345    102.274616
mercedes_benz  9011.639340   130683.161004    168.381339
audi           9738.588095   128602.179112    168.199043
ford           8161.758020   124166.666667    109.023013
renault        2661.171750   127199.036918     91.084002
peugeot        3270.620080   126184.738956    102.657028
fiat           2952.197087   116951.456311     80.998058

In [52]:
pd.pivot_table(popular_autos, index=['brand','vehicle_type'], 
               values=['name'],
               aggfunc=['count'])

                        count
                         name
brand      vehicle_type
audi       andere          14
           bus              3
           cabrio         269
           coupe          251
           kleinwagen     171
           kombi         1483
           limousine     1421
           suv             62
bmw        andere          25
           bus              6
           cabrio         485
           coupe          538
           kleinwagen      57
           kombi         1080
           limousine     2361
           suv            129
fiat       andere          21
           bus            100
           cabrio          49
           coupe           24
           kleinwagen     627
           kombi           35
           limousine      121
           suv              1
ford       andere          24
           bus            341
           cabrio          87
           coupe           89
           kleinwagen     884
           kombi          732
...                       ...
opel       cabrio         195
           coupe          171
           kleinwagen    1421
           kombi          875
           limousine      962
           suv             59
peugeot    andere           5
           bus             76
           cabrio         269
           coupe           36
           kleinwagen     490
           kombi          187
           limousine      126
           suv              8
renault    andere          15
           bus            359
           cabrio          71
           coupe           42
           kleinwagen     900
           kombi          246
           limousine      165
           suv             14
volkswagen andere          76
           bus           1276
           cabrio         388
           coupe          226
           kleinwagen    2195
           kombi         1605
           limousine     2491
           suv            224

[72 rows x 1 columns]

## Phase 5: Insights

In [53]:
autos['fuel_type'].value_counts()

benzin     26054
diesel     13049
lpg          605
cng           65
hybrid        37
elektro        8
andere         8
Name: fuel_type, dtype: int64